In [3]:
import tushare as ts
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### 使用tushare包获取某股票的历史行情数据

In [6]:
df = ts.get_k_data("600519",start="1988-01-01")
df.to_csv("600519.csv")

In [13]:
# 用date作为索引，只要需要的open（开盘价）、close（收盘价）、high（最高价）、low（最低价）
df = pd.read_csv("600519.csv", index_col="date",parse_dates=['date'])[['open','close','high','low']]

In [14]:
df

                open     close      high       low
date
2001-08-27     5.392     5.554     5.902     5.132
2001-08-28     5.467     5.759     5.781     5.407
2001-08-29     5.777     5.684     5.781     5.640
2001-08-30     5.668     5.796     5.860     5.624
2001-08-31     5.804     5.782     5.877     5.749
2001-09-03     5.812     5.779     5.870     5.757
2001-09-04     5.782     5.852     5.949     5.762
2001-09-05     5.876     5.849     5.924     5.813
2001-09-06     5.835     5.734     5.854     5.704
2001-09-07     5.702     5.574     5.773     5.570
2001-09-10     5.531     5.734     5.757     5.470
2001-09-11     5.749     5.670     5.773     5.656
2001-09-12     5.520     5.621     5.656     5.515
2001-09-13     5.626     5.607     5.671     5.577
2001-09-14     5.626     5.671     5.702     5.593
2001-09-17     5.637     5.599     5.670     5.546
2001-09-18     5.606     5.663     5.710     5.601
2001-09-19     5.671     5.768     5.768     5.634
2001-09-20     5.765     5.720     5.788     5.702
2001-09-21     5.668     5.634     5.718     5.624
2001-09-24     5.634     5.632     5.685     5.624
2001-09-25     5.668     5.660     5.709     5.632
2001-09-26     5.642     5.637     5.699     5.624
2001-09-27     5.637     5.734     5.777     5.624
2001-09-28     5.765     5.795     5.812     5.702
2001-10-08     5.781     5.715     5.809     5.663
2001-10-09     5.718     5.827     5.859     5.718
2001-10-10     5.827     5.640     5.848     5.629
2001-10-11     5.626     5.585     5.702     5.570
2001-10-12     5.609     5.624     5.726     5.320
...              ...       ...       ...       ...
2020-04-08  1152.000  1159.760  1166.310  1152.000
2020-04-09  1166.000  1158.500  1169.000  1147.960
2020-04-10  1157.880  1165.000  1181.500  1153.500
2020-04-13  1165.000  1162.300  1169.980  1148.500
2020-04-14  1176.000  1185.100  1191.550  1166.000
2020-04-15  1192.000  1189.600  1203.990  1187.100
2020-04-16  1192.970  1197.100  1197.100  1184.100
2020-04-17  1210.000  1226.000  1234.560  1205.010
2020-04-20  1221.000  1227.300  1231.500  1216.800
2020-04-21  1221.020  1200.000  1223.990  1193.000
2020-04-22  1206.000  1244.500  1249.500  1202.220
2020-04-23  1250.000  1252.260  1265.680  1247.770
2020-04-24  1248.000  1250.560  1259.890  1235.180
2020-04-27  1257.000  1276.000  1278.170  1250.960
2020-04-28  1285.310  1279.130  1299.940  1271.880
2020-04-29  1277.800  1274.900  1288.100  1258.000
2020-04-30  1271.000  1265.700  1285.010  1258.880
2020-05-06  1251.000  1300.000  1300.000  1250.000
2020-05-07  1299.400  1312.000  1314.990  1293.000
2020-05-08  1317.000  1314.610  1338.000  1308.510
2020-05-11  1320.000  1323.010  1335.000  1313.670
2020-05-12  1318.000  1333.000  1334.990  1316.000
2020-05-13  1333.000  1335.950  1337.990  1322.880
2020-05-14  1330.000  1326.590  1334.880  1325.110
2020-05-15  1329.000  1313.000  1333.500  1301.880
2020-05-18  1306.000  1346.210  1351.500  1305.130
2020-05-19  1364.000  1346.110  1364.000  1338.000
2020-05-20  1346.110  1351.000  1359.180  1336.810
2020-05-21  1355.000  1366.100  1371.960  1352.860
2020-05-22  1366.000  1328.200  1366.100  1322.880

[4470 rows x 4 columns]

### 输出该股票所有受怕比开票上涨3%的以上的日期

In [16]:
df[(df['close']-df['open'])/df['open']>=0.03].index

DatetimeIndex(['2001-08-27', '2001-08-28', '2001-09-10', '2001-12-21',
               '2002-01-18', '2002-01-31', '2003-01-14', '2003-10-29',
               '2004-01-05', '2004-01-14',
               ...
               '2019-09-12', '2019-09-18', '2020-02-11', '2020-03-02',
               '2020-03-05', '2020-03-10', '2020-04-02', '2020-04-22',
               '2020-05-06', '2020-05-18'],
              dtype='datetime64[ns]', name='date', length=311, freq=None)

### 输出该股票所有开票比前日受怕跌幅超过2%的日期

In [18]:
# shift移动位置，正1是往后移一位，负1是往前移一位，这样就可以前后比
df[(df['open']-df['close'].shift(1))/df['close'].shift(1)<=-0.02].index

DatetimeIndex(['2001-09-12', '2002-06-26', '2002-12-13', '2004-07-01',
               '2004-10-29', '2006-08-21', '2006-08-23', '2007-01-25',
               '2007-02-01', '2007-02-06', '2007-03-19', '2007-05-21',
               '2007-05-30', '2007-06-05', '2007-07-27', '2007-09-05',
               '2007-09-10', '2008-03-13', '2008-03-17', '2008-03-25',
               '2008-03-27', '2008-04-22', '2008-04-23', '2008-04-29',
               '2008-05-13', '2008-06-10', '2008-06-13', '2008-06-24',
               '2008-06-27', '2008-08-11', '2008-08-19', '2008-09-23',
               '2008-10-10', '2008-10-15', '2008-10-16', '2008-10-20',
               '2008-10-23', '2008-10-27', '2008-11-06', '2008-11-12',
               '2008-11-20', '2008-11-21', '2008-12-02', '2009-02-27',
               '2009-03-25', '2009-08-13', '2010-04-26', '2010-04-30',
               '2011-08-05', '2012-03-27', '2012-08-10', '2012-11-22',
               '2012-12-04', '2012-12-24', '2013-01-16', '2013-01-25',
               '2013-09-02', '2014-04-25', '2015-01-19', '2015-05-25',
               '2015-07-03', '2015-07-08', '2015-07-13', '2015-08-24',
               '2015-09-02', '2015-09-15', '2017-11-17', '2018-02-06',
               '2018-02-09', '2018-03-23', '2018-03-28', '2018-07-11',
               '2018-10-11', '2018-10-24', '2018-10-25', '2018-10-29',
               '2018-10-30', '2019-05-06', '2019-05-08', '2019-10-16',
               '2020-01-02', '2020-02-03', '2020-03-13', '2020-03-23'],
              dtype='datetime64[ns]', name='date', freq=None)

### 假如我从2021年1月1日开始，每月第一个交易日以开盘价（收盘价也可以）买入1手股票，每年最后一个交易日卖出所有股票，到今天为止，我的收益如何？

In [23]:
price_last = df['open'][-1]  # 最后一天的开盘价
df = df['2001-09':'2020-02']  # 删除首尾无用的数据，即没有月初或月末的
df

                open     close      high       low
date
2001-09-03     5.812     5.779     5.870     5.757
2001-09-04     5.782     5.852     5.949     5.762
2001-09-05     5.876     5.849     5.924     5.813
2001-09-06     5.835     5.734     5.854     5.704
2001-09-07     5.702     5.574     5.773     5.570
2001-09-10     5.531     5.734     5.757     5.470
2001-09-11     5.749     5.670     5.773     5.656
2001-09-12     5.520     5.621     5.656     5.515
2001-09-13     5.626     5.607     5.671     5.577
2001-09-14     5.626     5.671     5.702     5.593
2001-09-17     5.637     5.599     5.670     5.546
2001-09-18     5.606     5.663     5.710     5.601
2001-09-19     5.671     5.768     5.768     5.634
2001-09-20     5.765     5.720     5.788     5.702
2001-09-21     5.668     5.634     5.718     5.624
2001-09-24     5.634     5.632     5.685     5.624
2001-09-25     5.668     5.660     5.709     5.632
2001-09-26     5.642     5.637     5.699     5.624
2001-09-27     5.637     5.734     5.777     5.624
2001-09-28     5.765     5.795     5.812     5.702
2001-10-08     5.781     5.715     5.809     5.663
2001-10-09     5.718     5.827     5.859     5.718
2001-10-10     5.827     5.640     5.848     5.629
2001-10-11     5.626     5.585     5.702     5.570
2001-10-12     5.609     5.624     5.726     5.320
2001-10-15     5.609     5.515     5.624     5.452
2001-10-16     5.488     5.437     5.593     5.429
2001-10-17     5.435     5.343     5.438     5.296
2001-10-18     5.343     5.318     5.415     5.298
2001-10-19     5.312     5.234     5.335     5.157
...              ...       ...       ...       ...
2020-01-10  1109.000  1112.500  1115.990  1102.500
2020-01-13  1112.500  1124.270  1129.200  1112.000
2020-01-14  1124.200  1107.400  1124.890  1103.000
2020-01-15  1109.010  1112.130  1121.600  1105.000
2020-01-16  1118.870  1107.000  1118.870  1102.580
2020-01-17  1110.000  1107.500  1112.780  1101.010
2020-01-20  1111.860  1091.000  1111.860  1082.000
2020-01-21  1081.000  1075.300  1087.000  1072.300
2020-01-22  1070.000  1075.510  1084.000  1055.380
2020-01-23  1076.000  1052.800  1076.000  1037.000
2020-02-03   985.000  1003.920  1010.680   980.000
2020-02-04  1015.000  1038.010  1057.000  1011.010
2020-02-05  1050.000  1049.990  1054.000  1033.030
2020-02-06  1059.430  1071.000  1075.000  1052.020
2020-02-07  1070.010  1076.000  1077.000  1061.020
2020-02-10  1062.000  1066.490  1074.600  1057.200
2020-02-11  1063.000  1098.000  1099.680  1062.800
2020-02-12  1089.000  1097.270  1098.790  1085.880
2020-02-13  1098.000  1091.000  1113.890  1088.010
2020-02-14  1090.450  1088.000  1093.510  1083.110
2020-02-17  1082.500  1093.820  1096.190  1082.400
2020-02-18  1090.010  1084.000  1096.880  1083.000
2020-02-19  1085.000  1096.500  1101.500  1078.000
2020-02-20  1096.700  1118.000  1124.000  1095.410
2020-02-21  1111.460  1112.880  1123.540  1110.010
2020-02-24  1105.500  1087.180  1110.000  1085.500
2020-02-25  1078.000  1074.810  1082.090  1067.880
2020-02-26  1062.000  1073.700  1084.000  1055.000
2020-02-27  1076.000  1087.390  1094.990  1076.000
2020-02-28  1070.300  1057.000  1082.000  1049.970

[4409 rows x 4 columns]

In [31]:
df_monthly = df.resample("MS").first()  # 取第一个月,去掉S标识是末天的标识，但数据还是月初的
df_yearly = df.resample("A").last()[:-1]  # 取一年的最后交易日的值，并去掉没有12月的20年（现在时间是20年05月）

In [39]:
cost_money = 0  # 花多少钱
hold = 0  # 现在有多少股票
for year in range(2001,2021):
    cost_money += df_monthly[str(year)]['open'].sum()*100  # 每年第一个月买100股花的钱
    hold += len(df_monthly[str(year)]['open'])*100  # 持有的股票
    if year != 2020:  # 如果不是最后一年，则需要把股票卖出
        cost_money -= df_yearly[str(year)]['open'][0]*hold  # 获取开盘价并卖出去
        hold = 0
cost_money -= hold * price_last
print('最终赚了%d元'%(-cost_money))

最终赚了668979元